### ISSUE TITLE
Fetch-script fertig machen

### ISSUE THREAD

**Issue by JoFaHD** [JoFaHD/Kantine#11]
Mir war so als wären noch ein paar Macken in dem Script.
Ausserdem kann das Datum wieder aus dem Titel genommen werden.
Kann dann einfach so input1.xlsx heißen.

**Comment by Hypnoid** [comment]
My last commits should have solved this issue (correct me if I'm wrong). The only thing missing is documentation, which I'm about to add and which isn't vital to the functions of the script.
