### ISSUE TITLE
Migration Python => JS

### ISSUE THREAD

**Issue by JoFaHD** [JoFaHD/Kantine#28]
Ist aber nicht so wichtig.

Würde dann halt nur das xlsx -> Object mit Python
Eigentlicher Code mit JS
<br>
Wenn es sö wäre, wäre es besser sagt @Hypnoid.

**Comment by JoFaHD** [comment]
Informieren ueber DeepL JS API implementation und lernen wenn moeglich.
Maybe nachgucken ob easy weg fuer xlsx Parser in JS

**Comment by modernfaust** [comment]
js-xlsx NPM module interface would be easier to use. Seems like your current implementation is using Pandas excel reader, which is already very powerful.

**Comment by JoFaHD** [comment]
> js-xlsx NPM module interface would be easier to use. Seems like your current implementation is using Pandas excel reader, which is already very powerful. 

Yeah, that looks good! I'll try it out, thank you.
